#!/bin/sh

# Set timezone Asia/Jakarta (WIB)
uci set system.@system[0].zonename='Asia/Jakarta'
uci set system.@system[0].timezone='WIB-7'

# Enable NTP
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='0'

# Set Indonesian NTP pool
uci delete system.ntp.server
uci add_list system.ntp.server='0.id.pool.ntp.org'
uci add_list system.ntp.server='1.id.pool.ntp.org'
uci add_list system.ntp.server='2.id.pool.ntp.org'
uci add_list system.ntp.server='3.id.pool.ntp.org'

uci commit system

# Restart services
/etc/init.d/system restart
/etc/init.d/sysntpd restart

exit 0
